FEW_SHOT_STOP_TOKENS = ["\n\n"]
BASE_MODELS_SKIP_TASKS = ["mt-bench", "kalahi-mc"]
INSTRUCT_MODELS_SKIP_TASKS = []

INSTRUCT_NUM_IN_CONTEXT_EXAMPLES = 0
BASE_NUM_IN_CONTEXT_EXAMPLES = 5

PRAGMATICS_MIN_SCORE = 0.5
