abssum:
  metadata:
    version: 1
  name: abstractive_summarization
  competency: nlg
  metric_file: seahelm_tasks/nlg/abstractive_summarization/summarization.py
  metric_class: SummarizationMetric
  use_chrf_metric: false
  use_bertscore_metric: false
  use_rougeL_metric: true
  metric: normalized_rougel_f1
  temperature: 0.3
  languages:
    id:
      filepath: seahelm_tasks/nlg/abstractive_summarization/data/id_xlsum_100sample.jsonl
      example_filepath: seahelm_tasks/nlg/abstractive_summarization/data/id_xlsum_examples.jsonl
      max_tokens: 512
      prompt_template:
        template: |-
          Rangkumlah artikel bahasa Indonesia berikut ini ke dalam satu paragraf yang terdiri dari 1 atau 2 kalimat.

          Jawablah hanya dengan menggunakan format berikut ini:
          Rangkuman: $SUMMARY
          Ganti $SUMMARY dengan rangkumannya.{fewshot_examples}

          Artikel:
          ```
          {text}
          ```
        fewshot_example: |2-


          Artikel:
          ```
          {text}
          ```
          Rangkuman: {label}
        fewshot_label: 'Rangkuman: {label}'
    vi:
      filepath: seahelm_tasks/nlg/abstractive_summarization/data/vi_xlsum_100sample.jsonl
      example_filepath: seahelm_tasks/nlg/abstractive_summarization/data/vi_xlsum_examples.jsonl
      max_tokens: 512
      prompt_template:
        template: |-
          Tóm tắt bài báo Tiếng Việt dưới đây bằng một đoạn văn bao gồm 1 hay 2 câu.

          Chỉ trả lời bằng cách sử dụng định dạng sau:
          Bản tóm tắt: $SUMMARY
          Thay thế $SUMMARY bằng bản tóm tắt.{fewshot_examples}

          Bài báo:
          ```
          {text}
          ```
        fewshot_example: |2-


          Bài báo:
          ```
          {text}
          ```
          Bản tóm tắt: {label}
        fewshot_label: 'Bản tóm tắt: {label}'
    th:
      filepath: seahelm_tasks/nlg/abstractive_summarization/data/th_xlsum_100sample.jsonl
      example_filepath: seahelm_tasks/nlg/abstractive_summarization/data/th_xlsum_examples.jsonl
      max_tokens: 512
      prompt_template:
        template: |-
          จงสรุปบทความภาษาไทยต่อไปนี้ให้อยู่ในย่อหน้าด้วย 1 หรือ 2 ประโยค

          จงตอบตามรูปแบบดังต่อไปนี้:
          บทสรุป: $SUMMARY
          โดยจะต้องแทนที่ $SUMMARY ด้วยข้อความที่สรุปมาแล้ว{fewshot_examples}

          บทความ:
          ```
          {text}
          ```
        fewshot_example: |2-


          บทความ:
          ```
          {text}
          ```
          บทสรุป: {label}
        fewshot_label: 'บทสรุป: {label}'
    ta:
      filepath: seahelm_tasks/nlg/abstractive_summarization/data/ta_xlsum_100sample.jsonl
      example_filepath: seahelm_tasks/nlg/abstractive_summarization/data/ta_xlsum_examples.jsonl
      max_tokens: 512
      prompt_template:
        template: |-
          பின்வரும் தமிழ் கட்டுரையை 1 அல்லது 2 வாக்கியங்களில் ஒற்றைப் பத்தியாக சுருக்கி எழுதவும்.

          பின்வரும் பதில் வடிவமைப்பை மட்டும் பயன்படுத்தி பதிலளிக்கவும்:
          சுருக்கம்: $SUMMARY
          சுருக்கத்துடன் $SUMMARY ஐ மாற்றவும்.{fewshot_examples}

          கட்டுரை:
          ```
          {text}
          ```
        fewshot_example: |2-


          கட்டுரை:
          ```
          {text}
          ```
          சுருக்கம்: {label}
        fewshot_label: 'சுருக்கம்: {label}'
    tl:
      filepath: seahelm_tasks/nlg/abstractive_summarization/data/tl_xlsum.jsonl
      example_filepath: seahelm_tasks/nlg/abstractive_summarization/data/tl_xlsum_examples.jsonl
      max_tokens: 512
      prompt_template:
        template: |-
          Ibuod ang sumusunod na artikulong Filipino sa isang talata na may isa o dalawang pangungusap.

          Sumagot gamit ang sumusunod na format:
          Buod: $SUMMARY
          Palitan ang $SUMMARY ng buod.{fewshot_examples}

          Artikulo:
          ```
          {text}
          ```
        fewshot_example: |2-

          Artikulo:
          ```
          {text}
          ```
          Buod: {label}
        fewshot_label: 'Buod: {label}'
